sudo: false

language: node_js
node_js:
  - node # latest stable

env:
  - ELM_VERSION=0.19.0-bugfix2 ELM_TEST_VERSION=0.19.0-beta8

cache:
  directories:
    - sysconfcpus

install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install -g elm@${ELM_VERSION} elm-test@${ELM_TEST_VERSION}

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-test
